[package]
name = "pong-rs"
version = "1.0.0"
authors = ["gltchitm <42951031+gltchitm@users.noreply.github.com>"]
edition = "2021"

[dependencies]
rand = "0.8.4"

[dependencies.sdl2]
version = "0.35.1"
default-features = false
features = ["ttf"]
